//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Custom;

[assembly: RegisterDocumentType(Goodbye.CLASS_NAME, typeof(Goodbye))]

namespace CMS.DocumentEngine.Types.Custom
{
	/// <summary>
	/// Represents a content item of type Goodbye.
	/// </summary>
	public partial class Goodbye : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "custom.Goodbye";


		/// <summary>
		/// The instance of the class that provides extended API for working with Goodbye fields.
		/// </summary>
		private readonly GoodbyeFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// GoodbyeID.
		/// </summary>
		[DatabaseIDField]
		public int GoodbyeID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("GoodbyeID"), 0);
			}
			set
			{
				SetValue("GoodbyeID", value);
			}
		}


		/// <summary>
		/// Goodbye message.
		/// </summary>
		[DatabaseField]
		public string GoodbyeFarewell
		{
			get
			{
				return ValidationHelper.GetString(GetValue("GoodbyeFarewell"), @"");
			}
			set
			{
				SetValue("GoodbyeFarewell", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Goodbye fields.
		/// </summary>
		[RegisterProperty]
		public GoodbyeFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Goodbye fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class GoodbyeFields : AbstractHierarchicalObject<GoodbyeFields>
		{
			/// <summary>
			/// The content item of type Goodbye that is a target of the extended API.
			/// </summary>
			private readonly Goodbye mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="GoodbyeFields" /> class with the specified content item of type Goodbye.
			/// </summary>
			/// <param name="instance">The content item of type Goodbye that is a target of the extended API.</param>
			public GoodbyeFields(Goodbye instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// GoodbyeID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.GoodbyeID;
				}
				set
				{
					mInstance.GoodbyeID = value;
				}
			}


			/// <summary>
			/// Goodbye message.
			/// </summary>
			public string Farewell
			{
				get
				{
					return mInstance.GoodbyeFarewell;
				}
				set
				{
					mInstance.GoodbyeFarewell = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Goodbye" /> class.
		/// </summary>
		public Goodbye() : base(CLASS_NAME)
		{
			mFields = new GoodbyeFields(this);
		}

		#endregion
	}
}