//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Custom;

[assembly: RegisterDocumentType(Insult.CLASS_NAME, typeof(Insult))]

namespace CMS.DocumentEngine.Types.Custom
{
	/// <summary>
	/// Represents a content item of type Insult.
	/// </summary>
	public partial class Insult : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "custom.Insult";


		/// <summary>
		/// The instance of the class that provides extended API for working with Insult fields.
		/// </summary>
		private readonly InsultFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// InsultID.
		/// </summary>
		[DatabaseIDField]
		public int InsultID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("InsultID"), 0);
			}
			set
			{
				SetValue("InsultID", value);
			}
		}


		/// <summary>
		/// Make it hurt.
		/// </summary>
		[DatabaseField]
		public string InsultInsult
		{
			get
			{
				return ValidationHelper.GetString(GetValue("InsultInsult"), @"");
			}
			set
			{
				SetValue("InsultInsult", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Insult fields.
		/// </summary>
		[RegisterProperty]
		public InsultFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Insult fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class InsultFields : AbstractHierarchicalObject<InsultFields>
		{
			/// <summary>
			/// The content item of type Insult that is a target of the extended API.
			/// </summary>
			private readonly Insult mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="InsultFields" /> class with the specified content item of type Insult.
			/// </summary>
			/// <param name="instance">The content item of type Insult that is a target of the extended API.</param>
			public InsultFields(Insult instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// InsultID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.InsultID;
				}
				set
				{
					mInstance.InsultID = value;
				}
			}


			/// <summary>
			/// Make it hurt.
			/// </summary>
			public string Insult
			{
				get
				{
					return mInstance.InsultInsult;
				}
				set
				{
					mInstance.InsultInsult = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Insult" /> class.
		/// </summary>
		public Insult() : base(CLASS_NAME)
		{
			mFields = new InsultFields(this);
		}

		#endregion
	}
}